### ISSUE TITLE
error occurred in workerman and laravel5.3

### ISSUE THREAD

**Issue by xfan1015** [garveen/laravoole#11]
////======composer.json
{
    "require": {
        "php": ">=5.6.4",
	"garveen/laravoole": "dev-master",
        "laravel/framework": "5.3.*",
        "predis/predis": "~1.0",
        "guzzlehttp/guzzle": "~6.0",
        "barryvdh/laravel-ide-helper": "~2.2",
        "workerman/workerman": "^3.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
======//////

//////======php artisan laravoole  start====stdout
PHP Notice:  Use of undefined constant COMPOSER_INSTALLED - assumed 'COMPOSER_INSTALLED' in /home/wwwroot/sowechat/vendor/garveen/laravoole/src/Wrapper/WorkermanFastCGIWrapper.php on line 13
PHP Warning:  require(./workerman/workerman/Autoloader.php): failed to open stream: No such file or directory in /home/wwwroot/sowechat/vendor/garveen/laravoole/src/Wrapper/WorkermanFastCGIWrapper.php on line 13
PHP Fatal error:  require(): Failed opening required './workerman/workerman/Autoloader.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/sowechat/vendor/garveen/laravoole/src/Wrapper/WorkermanFastCGIWrapper.php on line 13
======//////

**Comment by garveen** [comment]
Please make a test with 0.2.2 and feedback.
