### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class App\Http\Kernel does not exist'

### ISSUE THREAD

**Issue by hhxsv5** [garveen/laravoole#20]
Hi,

If I changed Laravel root namespace like `php artisan app:name "Passport"`
Then `composer.json`
```JSON
{
"autoload": {
    "classmap": [
      "database"
    ],
    "psr-4": {
      "Passport\\": "app/"
    }
  }
}
```

But, there is hard code in file `Base.php` line 208
```PHP
$app->singleton(
    \Illuminate\Contracts\Http\Kernel::class,
    \App\Http\Kernel::class
);

$app->singleton(
    \Illuminate\Contracts\Console\Kernel::class,
    \App\Console\Kernel::class
);

$app->singleton(
    \Illuminate\Contracts\Debug\ExceptionHandler::class,
    \App\Exceptions\Handler::class
);
```

**Comment by hhxsv5** [comment]
Maybe we can reflect the root namespace.

**Comment by hhxsv5** [comment]
PR [#21](https://github.com/garveen/laravoole/pull/21)

**Comment by hhxsv5** [comment]
Release 0.2.5 is not corret without code of commit PR #21.

**Comment by garveen** [comment]
0.2.5 only fix the config error, and due to I am working on a new fastcgi processer, 0.2.6 will be released later.
By now, you can use dev-master to get latest code.
