### ISSUE TITLE
CLI mode

### ISSUE THREAD

**Issue by hhxsv5** [garveen/laravoole#23]
Example:
Function phpinfo() has different output between cli and cgi.
But laravoole is running under CLI mode, so far I think avoiding these functions is the only way.

**Comment by garveen** [comment]
So I cannot get the point of this issue... Could you explain it?

**Comment by hhxsv5** [comment]
phpinfo() outputs plain text instead of HTML when using the CLI mode.

this function has different output between cli and cgi.

So avoiding using these functions is the best way.

**Comment by garveen** [comment]
Issue is not comment or document. This should be a wiki or a PR.
