### ISSUE TITLE
feature: customized wrapper class support 

### ISSUE THREAD

**Issue by chxj1992** [garveen/laravoole#28]
It's an awesome package!
But sometimes I'd like to make some change on a wrapper to satisfy my own requirements (like doing someting before the swoole server started). So I think implement my wrapper might be a good idea.
And I also created a pr for this.  😁
#27

**Comment by garveen** [comment]
Your PR have some problems, so I implement this issue by another way. Please check if the commit functioning well and the version is 0.3.1.

**Comment by chxj1992** [comment]
good job, thx!
