### ISSUE TITLE
关于事件名变更问题

### ISSUE THREAD

**Issue by hhxsv5** [garveen/laravoole#31]
Hi，
laravoole.on_request更名为laravoole.requesting，因此项目已用于生产，所以此次影响较大，不过现在开始锁版本。

关于文档中的版本锁定：之前~0.2 表示>=0.2 && <=1.0，导致composer update时直接回升级到0.4.1。

**所以建议使用~0.4.1锁定到三级版本号，>=0.4.1&&<=0.5**

谢谢！

**Comment by garveen** [comment]
对你们的损失表示歉意。

用于生产的话建议用^0.2.0或0.2.*的格式进行版本号确定，这样在update的时候可以相对保证不会获得不向后兼容的变更，同时获得bug修复等更新。

我今晚会着手编写更新说明。

**Comment by garveen** [comment]
的确现在的readme会导致误导，届时一并处理。

**Comment by hhxsv5** [comment]
生产环境0.2.1上线后没有再次部署，也没啥损失，只是测试环境出现异常！

谢谢！
