### ISSUE TITLE
安装报错，求助

### ISSUE THREAD

**Issue by abellee** [garveen/laravoole#46]
Problem 1
    - Can only install one of: symfony/psr-http-message-bridge[v1.0.0, v0.2].
    - Can only install one of: symfony/psr-http-message-bridge[v1.0.0, v0.2].
    - Can only install one of: symfony/psr-http-message-bridge[v1.0.0, v0.2].
    - garveen/laravoole 0.5.1 requires symfony/psr-http-message-bridge ^1.0 -> satisfiable by symfony/psr-http-message-bridge[v1.0.0].
    - Installation request for garveen/laravoole ^0.5.1 -> satisfiable by garveen/laravoole[0.5.1].
    - Installation request for symfony/psr-http-message-bridge (locked at v0.2) -> satisfiable by symfony/psr-http-message-bridge[v0.2].

**Comment by denghongcai** [comment]
You most likely have incompatible versions of `laravel/framework`. Paste your `laravel/framework` version here.
