### ISSUE TITLE
websocket 模式怎么在控制器中获取swoole_websocket_server 和 fd

### ISSUE THREAD

**Issue by zeasly** [garveen/laravoole#48]
看代码好像是把swoole_websocket_server 和 fd对象放到了Request,但是我尝试获取缺获取不到

**Comment by ghost** [comment]
放到了 `app->singleton('laravoole.server')`

**Comment by niuniudada** [comment]
我也不懂，请问这个怎样才能获取得到呢？

**Comment by niuniudada** [comment]
我终于搞定了。

**Comment by sjyMystery** [comment]
怎么解决的呢

**Comment by niuniudada** [comment]
1、app('laravoole.server') 获取实例，直接用swoole提供的函数。
 eg: app('laravoole.server')->push(1, json_encode(['o' => 'ook']));

2、$request->getLaravooleInfo()->server->push($fd, json_encode(['o' => 'ook']))
我就是这样子用。

**Comment by sjyMystery** [comment]
然而我根本监听不到事件MMP
