### ISSUE TITLE
调用了不存在的方法，导致服务启动不起来

### ISSUE THREAD

**Issue by gaohuag** [garveen/laravoole#6]
src/Wrapper/SwooleHttpWrapper.php
第18行调用了不存在的方法set
        if (!empty($this->settings)) {
            $this->server->set($this->settings);
        }
$this->server的类型是swoole_http_server
可以参考文档：http://wiki.swoole.com/wiki/page/327.html

**Comment by garveen** [comment]
swoole_http_server继承于swoole_server
http://wiki.swoole.com/wiki/page/13.html

**Comment by gaohuag** [comment]
@garveen 我确实看到有继承 可是使用set的时候服务就起不起来.
$this->server变量的值：
`
object(swoole_http_server)#4 (7) {
  ["global":"swoole_http_server":private]=>
  int(0)
  ["connections"]=>
  object(swoole_connection_iterator)#5 (0) {
  }
  ["host"]=>
  string(7) "0.0.0.0"
  ["port"]=>
  int(11111)
  ["mode"]=>
  int(3)
  ["type"]=>
  int(1)
  ["ports"]=>
  array(1) {
    [0]=>
    object(swoole_server_port)#6 (3) {
      ["host"]=>
      string(7) "0.0.0.0"
      ["port"]=>
      int(11111)
      ["type"]=>
      int(1)
    }
  }
}`
$this->settings的值：
`array(3) {
  ["log_file"]=>
  string(49) "/opt/home/gaohua/testl/storage/logs/laravoole.log"
  ["daemonize"]=>
  int(1)
  ["max_request"]=>
  int(2000)
}`

**Comment by garveen** [comment]
各个日志发一下，包括php本身的

**Comment by garveen** [comment]
没有更多信息的话此issue即将关闭
