### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by niuniudada** [garveen/laravoole#64]
PHP版本：
PHP 7.1.10 (cli) (built: Oct 25 2017 09:42:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies
swoole版本：
swoole support => enabled
Version => 1.9.20
Author => tianfeng.han[email: mikan.tenny@gmail.com]
epoll => enabled
eventfd => enabled
timerfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
Linux Native AIO => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

切换服务器，部署后就出现以下报错。。。

不知道发生了什么事情。日志记录到的报错信息：
[2017-10-30 08:39:49] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Invalid argument supplied for foreach() in /data/wwwroot/huahui/vendor/garveen/laravoole/src/Request.php:118
Stack trace:
#0 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Request.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Invalid argumen...', '/data/wwwroot/h...', 118, Array)
#1 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Request.php(130): Laravoole\Request->destoryTempFiles()
#2 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Wrapper/SwooleWebSocketWrapper.php(225): Laravoole\Request->__destruct()
#3 [internal function]: Laravoole\Wrapper\SwooleWebSocketWrapper->onClose(Object(swoole_websocket_server), 770, 1)
#4 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Wrapper/Swoole.php(71): swoole_http_server->start()
#5 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Wrapper/SwooleHttpWrapper.php(26): Laravoole\Wrapper\Swoole->start()
#6 /data/wwwroot/huahui/vendor/garveen/laravoole/src/Wrapper/SwooleWebSocketWrapper.php(68): Laravoole\Wrapp in /data/wwwroot/huahui/vendor/garveen/laravoole/src/Request.php:118
Stack trace:
#0 {main}

**Comment by PickApig** [comment]
最后怎么解决的呢
