### ISSUE TITLE
Empty POST data

### ISSUE THREAD

**Issue by OSDDQD** [garveen/laravoole#7]
When I send POST request $request->get('field') is null but in GET request all works fine.
Little hack: $data = $request->all();
$data['field'] work.
Any ideas?

**Comment by garveen** [comment]
Cannot reproduce. Please paste testing code.

**Comment by OSDDQD** [comment]
`Route::post('/test', 'MiscController@test');`

```
    public function test(Request $request)
    {
        $data = $request->all();

        return response()->json([
            'data' => $data['test'],
            'plain' => $request->get('test'),
            'header' => $request->header('test')
        ]);
    }
```

And don't forget to disable csrf for this route.

```
   protected $except = [
        '/test*'
    ];
```

**Comment by OSDDQD** [comment]
Oh, if I use form-urlencode works fine, but I use Content-Type: application/json and doesn't work with this  content-type =(
Header:
`Content-Type: application/json`

**Comment by garveen** [comment]
So this is about POST as json.
Json support can be next feature, but I am working on websocket, so this would take weeks or months.

**Comment by OSDDQD** [comment]
https://medium.com/@paulredmond/how-to-submit-json-post-requests-to-lumen-666257fe8280
Solve my problem by adding middleware.
We can close this issue, thanks.

**Comment by denghongcai** [comment]
try to use 

```
$request->json()->get('field')
```

Lumen is a little different with Laravel

**Comment by OSDDQD** [comment]
@denghongcai link I gave above is suitable for both.
I choose solution with middleware.
